# see these links for more info on MIME types:
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
# https://www.iana.org/assignments/media-types/media-types.xhtml

# from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types
MIME_TYPES_BASIC = [
    'application/epub+zip',
    'application/gzip',
    'application/java-archive',
    'application/json',
    'application/ld+json',
    'application/msword',
    'application/octet-stream',
    'application/ogg',
    'application/pdf',
    'application/php',
    'application/rtf',
    'application/vnd.amazon.ebook',
    'application/vnd.apple.installer+xml',
    'application/vnd.mozilla.xul+xml',
    'application/vnd.ms-excel',
    'application/vnd.ms-fontobject',
    'application/vnd.ms-powerpoint',
    'application/vnd.oasis.opendocument.presentation',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.visio',
    'application/x-7z-compressed',
    'application/x-abiword',
    'application/x-bytecode.python',
    'application/x-bzip',
    'application/x-bzip2',
    'application/x-csh',
    'application/x-freearc',
    'application/x-rar-compressed',
    'application/x-sh',
    'application/x-shockwave-flash',
    'application/x-tar',
    'application/xhtml+xml',
    'application/xml',
    'application/zip',
    'audio/3gpp',
    'audio/3gpp2',
    'audio/aac',
    'audio/midi audio/x-midi',
    'audio/mpeg',
    'audio/ogg',
    'audio/opus',
    'audio/wav',
    'audio/webm',
    'font/otf',
    'font/ttf',
    'font/woff',
    'font/woff2',
    'image/bmp',
    'image/gif',
    'image/jpeg',
    'image/png',
    'image/svg+xml',
    'image/tiff',
    'image/vnd.microsoft.icon',
    'image/webp',
    'text/calendar',
    'text/css',
    'text/csv',
    'text/html',
    'text/javascript',
    'text/javascript',
    'text/plain',
    'text/xml',
    'video/3gpp',
    'video/3gpp2',
    'video/mp2t',
    'video/mpeg',
    'video/ogg',
    'video/webm',
    'video/x-msvideo'
]

# add any specialized MIME types to this list
MIME_TYPES = MIME_TYPES_BASIC + [
    'text/x-c',
    'text/x-h',
    'text/x-java-source',
    'text/x-script.phyton',
]
